name: gch_cityservice
description: GCH Cityservice application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

  http: ^0.12.0+2
  google_maps_flutter: ^0.5.7
  latlong: ^0.6.1
  sliding_up_panel: ^0.3.4
  location: ^2.3.5
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_screenutil: ^0.5.2
  firebase_core: ^0.3.0
  firebase_analytics: ^1.1.0
  firebase_database: ^1.0.5
  firebase_auth: ^0.8.0
  firebase_storage: ^2.1.0+1
  intro_views_flutter: ^2.6.0
  google_places_picker: ^2.0.1
  multi_image_picker: ^4.2.0
  progress_hud: ^1.1.0
  path_provider: ^0.5.0+1

dev_dependencies:
  flutter_launcher_icons: "^0.7.0"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
        - asset: assets/fonts/BebasNeue-Thin.ttf
        - asset: assets/fonts/BebasNeue-Bold.ttf
          weight: 700
        - asset: assets/fonts/BebasNeue-Book.ttf
        - asset: assets/fonts/BebasNeue-Light.ttf
          weight: 300

  assets:
    - assets/images/map-marker-green.png
    - assets/images/map-marker-grey.png
    - assets/images/map-marker-red.png
    - assets/icons/icon.png
    - assets/images/intro/back.png
    - assets/images/intro/intro_1.png
    - assets/images/intro/intro_2.png
    - assets/images/intro/intro_3.png

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
